# Generated by Django 3.1.6 on 2021-02-24 19:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_household_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to=core.models.grocery_image_file_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='household',
            name='users',
        ),
        migrations.AddField(
            model_name='household',
            name='grocery_list',
            field=models.ManyToManyField(related_name='grocery', to='core.Grocery'),
        ),
        migrations.AddField(
            model_name='household',
            name='shopping_list',
            field=models.ManyToManyField(related_name='shopping', to='core.Grocery'),
        ),
    ]
