# Generated by Django 3.1.6 on 2021-02-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210228_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='grocery_list',
            field=models.ManyToManyField(default=None, null=True, related_name='grocery', to='core.Grocery'),
        ),
        migrations.AlterField(
            model_name='household',
            name='shopping_list',
            field=models.ManyToManyField(default=None, null=True, related_name='shopping', to='core.Grocery'),
        ),
    ]
